Graeme dev2
moka-guys/bedfile_editor pull request #3
Opened 2021-08-24 16:26 UTC by Graeme-Smith

A test version of this tool can be found at https://test-bedmaker2.herokuapp.com/

NOTE: THere is no need to review files in the folders named static or staticfiles as these contain CSS and javascript files which are part of the bootstrap 4 framework.

Miscellaneous changes:

Added vscode files to .gitignore file
Updated Admin page
Website styling:

Added html templates for base, home, import, and view
Setup base template with navbar
Added datatables to display imported data
Database:

Added models for BedfileRequest, Gene, and Transcript to database
Getting Data:

Web form to upload ensembl gene IDs and Bedfile Request meta data
Get gene details from Ensembl API
Get RefSeq stable ID/MANE details from TARK API
Deployment:

Configured for Heroku deployment

2021-08-31 12:15 UTC, aledj2 requested changes
> Reviewed 20 of 1073 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/bedfile_editor/3)* status: 20 of 1073 files reviewed, 16 unresolved discussions (waiting on @Graeme-Smith, @natashapinto, @preciserobot, and @rebeccahaines1)

___
*[requirements.txt, line 6 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-Mhx4X022wczS4EJrfH3:-Mhx4X022wczS4EJrfH4:bfopn9m) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/requirements.txt#L6)):*
> ```help
> environs
> gunicorn
> pandas
> ```

can we add version numbers to these packages?
___
*[bed_maker/forms.py, line 25 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-Mhx9dux4bVe6oIZUGTv:-Mhx9dux4bVe6oIZUGTw:b-ddb91t) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/forms.py#L25)):*
> ```
> elf.helper.label_class = 'col-lg-2'
> ```
is it possible/ helpful to descibe why this value has been set? or what it means?
___
*[bed_maker/forms.py, line 26 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-Mhx9kZk2sccob-0svrP:-Mhx9kZk2sccob-0svrQ:blmy6pl) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/forms.py#L26)):*
> ```Python
>         self.helper.form_id = 'manual-upload-form'
>         self.helper.label_class = 'col-lg-2'
>         self.helper.field_class = 'col-lg-10'
> ```

is it possible/ helpful to descibe why this value has been set? or what it means?
___
*[bed_maker/models.py, line 3 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiQtUQyBgBROWaTb2Uh:-MiQtUQyBgBROWaTb2Ui:bz18otj) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/models.py#L3)):*
> ```Python
> from django.db import models
> 
> # Create your models here.
> ```

have requested a db schema (in a seperate file)
___
*[bed_maker/views.py, line 22 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR-q-q3mv7Qby0YFaF:-MiR-q-q3mv7Qby0YFaG:b-3o6p22) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L22)):*
> ```Python
>     return render(request, 'bed_maker/view.html', {'transcripts': transcript_list})
> 
> def get_MANE_list():
> ```

docstring please
___
*[bed_maker/views.py, line 27 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR-bwlBViJwCEcdOuz:-MiR-bwlBViJwCEcdOv-:bf5097) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L27)):*
> ```Python
>     ext = f"/api/transcript/manelist/"
>     
>     r = requests.get(server+ext, headers={ "Content-Type" : "text/html"})
> ```

could we use os.path.join to do this (not sure if os is the best package)
___
*[bed_maker/views.py, line 30 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR-VzH0fecGZEYoGC9:-MiR-VzH0fecGZEYoGCA:b-yejo9j) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L30)):*
> ```Python
>     
>     if not r.ok:
>         r.raise_for_status()
> ```

what happens here?
___
*[bed_maker/views.py, line 39 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR-u-K7G8sBfAscrQO:-MiR-u-K7G8sBfAscrQP:b-3rwsaw) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L39)):*
> ```Python
>     return(MANE_list_df)  
> 
> def lookup_ensembl_gene(ensembl_gene_id):
> ```

docstring pelase
___
*[bed_maker/views.py, line 44 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR03hf6xDfb9LdyBGb:-MiR03hf6xDfb9LdyBGc:b9vefg8) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L44)):*
> ```Python
>     ext = f"/lookup/id/{ensembl_gene_id}?expand=1&utr=1"
>     
>     r = requests.get(server+ext, headers={ "Content-Type" : "application/json"})
> ```

Is there a more relibale/standard way of joining paths (above I suggested os.path.join)
___
*[bed_maker/views.py, line 47 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR0U4G053kxSG-9fRF:-MiR0U4G053kxSG-9fRG:bcqxrc5) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L47)):*
> ```Python
>     
>     if not r.ok:
>         r.raise_for_status()
> ```

as above, what does this do?
___
*[bed_maker/views.py, line 65 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR15nh571-MocnEGHx:-MiR15nh571-MocnEGHy:bkytwqi) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L65)):*
> ```Python
>     if request.method == 'POST':
> 
>         import_form = ManualUploadForm(request.POST)
> ```

is import_form not created above?
___
*[bed_maker/views.py, line 71 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR1S9I8rfBUplETUNT:-MiR1S9I8rfBUplETUNU:b-ywh276) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L71)):*
> ```Python
> 
>            # get bedfile request data
>             bedfile_request, created = BedfileRequest.objects.get_or_create(
> ```

where does bedffilerequestcome from?
___
*[bed_maker/views.py, line 83 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR1fiW4ZJ17jhMUOXb:-MiR1fiW4ZJ17jhMUOXc:b770tui) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L83)):*
> ```Python
> 
>             # Get Gene list
>             gene_list = [y for y in (x.strip() for x in cleaned_data['gene_list'].splitlines()) if y]
> ```

cleaned_data['gene_list']is a list of ensembl ids, one per line? we're turning it into a list and removing any empty lines or whitespace?(list comprehension isn't my strongsuit)
___
*[bed_maker/views.py, line 85 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR2sZO588ZUxFt3xF2:-MiR2sZO588ZUxFt3xF3:b-98q95x) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L85)):*
> ```Python
>             gene_list = [y for y in (x.strip() for x in cleaned_data['gene_list'].splitlines()) if y]
>             for gene_ID in gene_list:
>                 gene = Gene.objects.create(
> ```

What is Gene.objects? 
___
*[bed_maker/views.py, line 94 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR4m2D1s0EIFt-C_Xb:-MiR4m2D1s0EIFt-C_Xc:b-9m2nvp) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L94)):*
> ```Python
>                     if transcript_dict["id"] in MANE_list_df.ens_stable_id.values:
>                         MANE_transcript = 'True'
>                         RefSeq_transcript_id = MANE_list_df.loc[MANE_list_df['ens_stable_id'] == transcript_dict["id"]]['refseq_stable_id'].item()
> ```

there's no if here. I haven't seen this before
___
*[config/settings.py, line 33 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiQt8nw2lJwVz6ixHVB:-MiQt8nw2lJwVz6ixHVC:b-5a2s2) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/config/settings.py#L33)):*
> ```Python
> DEBUG = env.bool("DJANGO_DEBUG")
> 
> ALLOWED_HOSTS = ['.herokuapp.com', 'localhost', '127.0.0.1']
> ```

in future could this be imported from a file not in version control?


<!-- Sent from Reviewable.io -->

2021-08-31 14:44 UTC, Graeme-Smith commented
___
*[config/settings.py, line 33 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiQt8nw2lJwVz6ixHVB:-MiReGeADKK05Jkt40Sk:bcs4hl2) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/config/settings.py#L33)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

in future could this be imported from a file not in version control?
</blockquote></details>

I've created a .env file for saving an variables outside version control - I will probably move ALLOWED_HOSTS there when I start doing development on the GenApp server.


<!-- Sent from Reviewable.io -->

2021-08-31 14:50 UTC, Graeme-Smith commented
___
*[requirements.txt, line 6 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-Mhx4X022wczS4EJrfH3:-MiRerOVEjV_d3aFntFc:b6gbx6u) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/requirements.txt#L6)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can we add version numbers to these packages?
</blockquote></details>

I was going to add versions  to the packages once development is a bit more mature - at some point I will dockerise the environment for easier deployment and I was going to include versions in that step, didn't want to duplicate this twice. (Part of the problem is that the modules in my dev env are installed via miniconda, not pip3, so requirements.txt not created automatically)


<!-- Sent from Reviewable.io -->

2021-08-31 14:57 UTC, Graeme-Smith commented
___
*[bed_maker/models.py, line 3 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiQtUQyBgBROWaTb2Uh:-MiRhfT_DiagzP5cy2Io:bjwfyfz) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/models.py#L3)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

have requested a db schema (in a seperate file)
</blockquote></details>

Please see https://dbdiagram.io/d/6126ad736dc2bb6073bb8ddd


<!-- Sent from Reviewable.io -->

2021-08-31 16:04 UTC, Graeme-Smith commented
___
*[bed_maker/views.py, line 92 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiRwZbQ9rE50ywLrDDh:-MiRwZbQ9rE50ywLrDDi:be3sh6r) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L92)):*
The if staement starts at:
> ```
>  if transcript_dict["id"] in MANE_list_df.ens_stable_id.values:

> ```


<!-- Sent from Reviewable.io -->

2021-08-31 16:10 UTC, Graeme-Smith commented
___
*[bed_maker/forms.py, line 25 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-Mhx9dux4bVe6oIZUGTv:-MiRxxJ8C7vZlTEbXvk_:btlhycv) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/forms.py#L25)):*
> ```
> self.helper.label_class = 'col-lg-2'
> ```
I've added a comment explaining this is from Cripsy Forms


<!-- Sent from Reviewable.io -->

2021-08-31 16:18 UTC, Graeme-Smith commented
___
*[bed_maker/views.py, line 47 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR0U4G053kxSG-9fRF:-MiRzxIx77Poqkg5f4h0:b-kt0g80) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L47)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

as above, what does this do?
</blockquote></details>

Built in status lookup object - If we made a bad request (a 4XX client error or 5XX server error response), we can raise it with Response.raise_for_status(), it will then give use an informative error message.


<!-- Sent from Reviewable.io -->

2021-08-31 16:20 UTC, Graeme-Smith commented
___
*[bed_maker/views.py, line 71 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR1S9I8rfBUplETUNT:-MiS-OGW7K9ZMqfEQGYm:buch90i) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L71)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

where does bedffilerequestcome from?
</blockquote></details>

BedfileRequest is created when the users files in the Import details in the webapp - basically it creates a BedfileRequest object which is defined in models.py


<!-- Sent from Reviewable.io -->

2021-08-31 16:22 UTC, Graeme-Smith commented
___
*[bed_maker/views.py, line 83 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR1fiW4ZJ17jhMUOXb:-MiS-x6F-4gYHW_URKKI:boqhg94) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L83)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

cleaned_data['gene_list']is a list of ensembl ids, one per line? we're turning it into a list and removing any empty lines or whitespace?(list comprehension isn't my strongsuit)
</blockquote></details>

Yep, your synopsis is correct.


<!-- Sent from Reviewable.io -->

2021-08-31 16:57 UTC, Graeme-Smith commented
___
*[bed_maker/views.py, line 65 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR15nh571-MocnEGHx:-MiS1VA_4V0FqBugG4_7:b-713a6n) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L65)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

is import_form not created above?
</blockquote></details>

The second import_form is required to make the form interactive, basically when the user submits the form import_form is created again - not sure why I've named it the same twice - whether this is required or even a desirable thing.  If we keep it as it is for this version I will make a note to look at it in the next release.


<!-- Sent from Reviewable.io -->

2021-08-31 16:57 UTC, Graeme-Smith reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/bedfile_editor/3)* status: all files reviewed, 17 unresolved discussions (waiting on @aledj2, @natashapinto, and @rebeccahaines1)

___
*[bed_maker/forms.py, line 26 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-Mhx9kZk2sccob-0svrP:-MiRyNcr1J7LN3fFeQRU:b-hlb6hm) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/forms.py#L26)):*
> I've added a comment explaining this is from Cripsy Forms
___
*[bed_maker/views.py, line 22 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR-q-q3mv7Qby0YFaF:-MiRqUAa438sPgMt-BzD:b-896fix) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L22)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

docstring please
</blockquote></details>

Done.
___
*[bed_maker/views.py, line 27 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR-bwlBViJwCEcdOuz:-MiRte2a3WFxvTvUKosn:b-s601dm) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L27)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

could we use os.path.join to do this (not sure if os is the best package)
</blockquote></details>

Not sure if os.path.join would be helpful here - that module  ensures that a file path is readable to the underlying OS no matter the formatting - this is a call to a a API URL. The code is taken directly from the Ensembl REST API examples https://rest.ensembl.org/documentation/info/lookup - even though this uses the TARK API I went for consistency in the code between all the API calls.
___
*[bed_maker/views.py, line 30 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR-VzH0fecGZEYoGC9:-MiS0kTCDhphf0u9e04p:bbarxy1) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L30)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

what happens here?
</blockquote></details>

Provides a meaningful error message if server returns a 4**, 5** response.
___
*[bed_maker/views.py, line 39 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR-u-K7G8sBfAscrQO:-MiRyuRP8lKJsxnmUE8s:b-896fix) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L39)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

docstring pelase
</blockquote></details>

Done.
___
*[bed_maker/views.py, line 44 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR03hf6xDfb9LdyBGb:-MiRvtlh7mUDiWcJGUeu:b-mw3gzz) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L44)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Is there a more relibale/standard way of joining paths (above I suggested os.path.join)
</blockquote></details>

Not sure if os.path.join would be helpful here - that module  ensures that a file path is readable to the underlying OS no matter the formatting - this is a call to a a API URL. The code is taken directly from the Ensembl REST API examples https://rest.ensembl.org/documentation/info/lookup 
___
*[bed_maker/views.py, line 85 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR2sZO588ZUxFt3xF2:-MiS0AIq924Bv8rM2CDB:bfnirbd) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L85)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

What is Gene.objects? 
</blockquote></details>

Gene objects is defined in models.py - it populates the data into the genes table for every BedfileRequest made.
___
*[bed_maker/views.py, line 94 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR4m2D1s0EIFt-C_Xb:-MiRwT8b5BdmWfqH35sy:bbi7gp) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L94)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

there's no if here. I haven't seen this before
</blockquote></details>

See note above for start of IF statement


<!-- Sent from Reviewable.io -->

2021-09-01 09:21 UTC, aledj2 requested changes
> Reviewed 1 of 1073 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/bedfile_editor/3)* status: all files reviewed (commit messages unreviewed), 12 unresolved discussions (waiting on @aledj2, @Graeme-Smith, @natashapinto, and @rebeccahaines1)

___
*[requirements.txt, line 6 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-Mhx4X022wczS4EJrfH3:-MiVQbc-39ClqRQyc61R:bp7vrzz) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/requirements.txt#L6)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

I was going to add versions  to the packages once development is a bit more mature - at some point I will dockerise the environment for easier deployment and I was going to include versions in that step, didn't want to duplicate this twice. (Part of the problem is that the modules in my dev env are installed via miniconda, not pip3, so requirements.txt not created automatically)
</blockquote></details>

ok, can we make sure this is done befire it goes live? I'll open an issue
___
*[bed_maker/models.py, line 3 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiQtUQyBgBROWaTb2Uh:-MiVcwcj8zBKawd-xZEA:b-b0l2j9) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/models.py#L3)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Please see https://dbdiagram.io/d/6126ad736dc2bb6073bb8ddd
</blockquote></details>

added as an issue for future
___
*[bed_maker/views.py, line 22 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR-q-q3mv7Qby0YFaF:-MiVdKvL9HnOF1L3bE5v:b-u05vci) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L22)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

can't see it.
___
*[bed_maker/views.py, line 30 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR-VzH0fecGZEYoGC9:-MiVdRwKB5NK1qPJfdg-:b-eefi1q) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L30)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Provides a meaningful error message if server returns a 4**, 5** response.
</blockquote></details>

can you add this as a comment rather than on the PR
___
*[bed_maker/views.py, line 39 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR-u-K7G8sBfAscrQO:-MiVdUyiE4oVyseWh4y6:b-cfa4tc) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L39)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

can't see it
___
*[bed_maker/views.py, line 47 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR0U4G053kxSG-9fRF:-MiVdXXf8drO6Xip_qvp:b-1nblnm) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L47)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Built in status lookup object - If we made a bad request (a 4XX client error or 5XX server error response), we can raise it with Response.raise_for_status(), it will then give use an informative error message.
</blockquote></details>

as above, please add as comment
___
*[bed_maker/views.py, line 65 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR15nh571-MocnEGHx:-MiVdbr71qlr_edqphpd:bb1pza3) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L65)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

The second import_form is required to make the form interactive, basically when the user submits the form import_form is created again - not sure why I've named it the same twice - whether this is required or even a desirable thing.  If we keep it as it is for this version I will make a note to look at it in the next release.
</blockquote></details>

raised as issue #6 
___
*[bed_maker/views.py, line 71 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR1S9I8rfBUplETUNT:-MiVdsFaEIAgjWvuaTap:bef6oye) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L71)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

BedfileRequest is created when the users files in the Import details in the webapp - basically it creates a BedfileRequest object which is defined in models.py
</blockquote></details>

can responses like this be made in the comments please
___
*[bed_maker/views.py, line 83 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR1fiW4ZJ17jhMUOXb:-MiVdvf504rdF8JQB_TC:b28i6zs) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L83)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Yep, your synopsis is correct.
</blockquote></details>

can this be added as a comment please
___
*[bed_maker/views.py, line 85 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR2sZO588ZUxFt3xF2:-MiVe1Ti9Ep14OXz_A8N:b28i6zs) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L85)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Gene objects is defined in models.py - it populates the data into the genes table for every BedfileRequest made.
</blockquote></details>

can this be added as a comment please
___
*[bed_maker/views.py, line 94 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR4m2D1s0EIFt-C_Xb:-MiVe9nZCHq3YbjkrCbE:bsdliyh) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L94)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

See note above for start of IF statement
</blockquote></details>

sorry, I still don't understand this line. your setting refseq_transcript_id to the value of a comparison? does that mean it's True or False?


<!-- Sent from Reviewable.io -->

2021-09-07 16:55 UTC, Graeme-Smith commented
___
*[bed_maker/views.py, line 94 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR4m2D1s0EIFt-C_Xb:-Mj05bETEz4TLfdpOd03:b6gv0u) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L94)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

sorry, I still don't understand this line. your setting refseq_transcript_id to the value of a comparison? does that mean it's True or False?
</blockquote></details>

Ah, I think I see the confusion.  Its assigning 'False' with =, not checking for equivalence to False with ==.  This If statement checks if the the Transcript ID is   present in a list of all MANE transcripts, if it does it allocates True to the  field MANE_transcript and adds the appropriate RefSeq ID to the field RefSeq_transcript_id - the else statement assigns 'false' and '' to these columns accordingly.  In the next reiteration this will be changed from boolean True/False to "MANE SELECT", "MANE PLUS CLINICAL", and null.


<!-- Sent from Reviewable.io -->

2021-09-07 16:56 UTC, Graeme-Smith reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/bedfile_editor/3)* status: 1072 of 1073 files reviewed, 11 unresolved discussions (waiting on @aledj2, @natashapinto, @preciserobot, and @rebeccahaines1)

___
*[bed_maker/views.py, line 22 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR-q-q3mv7Qby0YFaF:-Mj04D6q4inEOa9chiA7:b-896fix) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L22)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can't see it.
</blockquote></details>

Done.
___
*[bed_maker/views.py, line 30 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR-VzH0fecGZEYoGC9:-Mj04Kw75iPqGwsUhAau:b-896fix) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L30)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can you add this as a comment rather than on the PR
</blockquote></details>

Done.
___
*[bed_maker/views.py, line 39 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR-u-K7G8sBfAscrQO:-Mj04SYB9YDdV7qcpSKg:b-896fix) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L39)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can't see it
</blockquote></details>

Done.
___
*[bed_maker/views.py, line 47 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR0U4G053kxSG-9fRF:-Mj03_sM4F32HUu4PSCx:b-896fix) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L47)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

as above, please add as comment
</blockquote></details>

Done.
___
*[bed_maker/views.py, line 71 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR1S9I8rfBUplETUNT:-Mj04lU35-26dpGWfgG-:b-896fix) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L71)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can responses like this be made in the comments please
</blockquote></details>

Done.
___
*[bed_maker/views.py, line 83 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR1fiW4ZJ17jhMUOXb:-Mj059C96B0rQmls4FzN:b-896fix) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L83)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can this be added as a comment please
</blockquote></details>

Done.
___
*[bed_maker/views.py, line 85 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR2sZO588ZUxFt3xF2:-Mj05Idb78S4YOHGecDl:b-896fix) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L85)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can this be added as a comment please
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-14 13:48 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/bedfile_editor/3)* status: 1072 of 1073 files reviewed, 6 unresolved discussions (waiting on @aledj2, @Graeme-Smith, @natashapinto, @preciserobot, and @rebeccahaines1)

___
*[bed_maker/views.py, line 71 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR1S9I8rfBUplETUNT:-MjZYZ_O3_RXqveR212b:bl3jx0o) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L71)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sorry, still can't see this comment in the code
___
*[bed_maker/views.py, line 83 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR1fiW4ZJ17jhMUOXb:-MjZYTcYEpsyEISLZR3J:bl3jx0o) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L83)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sorry, still can't see this comment in the code
___
*[bed_maker/views.py, line 85 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR2sZO588ZUxFt3xF2:-MjZYRBzD2FfE8M5sYvJ:bl3jx0o) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L85)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sorry, still can't see this comment in the code
___
*[bed_maker/views.py, line 94 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR4m2D1s0EIFt-C_Xb:-MjZYAHF-qVsDSRrVkJN:b-2dyjmf) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L94)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Ah, I think I see the confusion.  Its assigning 'False' with =, not checking for equivalence to False with ==.  This If statement checks if the the Transcript ID is   present in a list of all MANE transcripts, if it does it allocates True to the  field MANE_transcript and adds the appropriate RefSeq ID to the field RefSeq_transcript_id - the else statement assigns 'false' and '' to these columns accordingly.  In the next reiteration this will be changed from boolean True/False to "MANE SELECT", "MANE PLUS CLINICAL", and null.
</blockquote></details>

thanks, I follow that now. but I'm afraid I  still can't see this comment in the code


<!-- Sent from Reviewable.io -->

2021-09-14 14:43 UTC, Graeme-Smith reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/bedfile_editor/3)* status: 1072 of 1073 files reviewed, 6 unresolved discussions (waiting on @aledj2, @natashapinto, @preciserobot, and @rebeccahaines1)

___
*[bed_maker/views.py, line 71 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR1S9I8rfBUplETUNT:-MjZgq02E_S7YJsgieWb:b-896fix) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L71)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

sorry, still can't see this comment in the code
</blockquote></details>

Done.
___
*[bed_maker/views.py, line 83 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR1fiW4ZJ17jhMUOXb:-MjZifCZ6fgJt2vWpwmC:b-896fix) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L83)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

sorry, still can't see this comment in the code
</blockquote></details>

Done.
___
*[bed_maker/views.py, line 85 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR2sZO588ZUxFt3xF2:-MjZi95g569h5q57SCPG:b-896fix) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L85)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

sorry, still can't see this comment in the code
</blockquote></details>

Done.
___
*[bed_maker/views.py, line 94 at r1](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-MiR4m2D1s0EIFt-C_Xb:-MjZjX-X36xc0RS8esWv:b-896fix) ([raw file](https://github.com/moka-guys/bedfile_editor/blob/947b6bdcc76c3ae647ba138bad81ce9ee705f741/bed_maker/views.py#L94)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

thanks, I follow that now. but I'm afraid I  still can't see this comment in the code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-17 09:06 UTC, aledj2 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/moka-guys/bedfile_editor/3#-:-Mjn-NDi7udEpv1u_cf6:bg7igkv)* status: 1072 of 1073 files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith, @natashapinto, @preciserobot, and @rebeccahaines1)



<!-- Sent from Reviewable.io -->

2021-09-17 09:06 UTC, aledj2 approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/bedfile_editor/3)* status: all files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith, @natashapinto, and @rebeccahaines1)



<!-- Sent from Reviewable.io -->

2021-09-17 09:15 UTC, merged